FROM python:3.10

WORKDIR /app


COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


COPY backend/ ./


COPY frontend/templates/ ./templates/


ENV FLASK_ENV=development
ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
